name: Test, build, lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_n_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v ./...

    - name: Vet
      run: go vet ./...

    - name: Staticcheck
      uses: dominikh/staticcheck-action@v1.1.0
      with:
        version: "2021.1.1"

    - name: Build
      run: GOOS=darwin GOARCH=amd64 go build -v ./cmd/danlisp

    - name: Auto-release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Latest Build"
        files: |
          danlisp
